language: python
sudo: true
python:
  - "3.5"
  - "3.6"
sudo: false
install:
  - pip install -U pip setuptools wheel codecov coverage
  - pip install -Ue ".[dev]"
script:
  - bash .travis.sh $JOB
cache:
  directories:
    - $HOME/.cache/pip
services:
  - postgresql
env:
  - JOB=tests
  - JOB=style
  - JOB=docs
addons:
  postgresql: "9.6"
